REFRESH_TIME: 10000

SERVERS:
  SERVER_1:
    ADDRESS: "176.57.168.195:28315"
    WHITELIST_BOT: yes
    STATUS_BOT: yes
  SERVER_2:
    ADDRESS: "176.57.140.83:28315"
    WHITELIST_BOT: yes
    STATUS_BOT: yes
  SERVER_3:
    ADDRESS: "176.57.173.2:28415"
    WHITELIST_BOT: no
    STATUS_BOT: yes

STATUS_BOT:
  WEBHOOK: "https://discord.com/api/webhooks/999897001737072761/B3iKcFXh0kO9aa-X0SV5Qq1Q_3fwufW_7KuDObNLSHq5CXtY_vNVTTAmQDV3hMuPF8pe"